### ISSUE TITLE
latest distribution cannot be built WITH ant tool

### ISSUE THREAD

**Issue by haobug** [openintents/distribution#6]
please refer to https://github.com/openintents/filemanager/issues/53
for further detail.

**Comment by haobug** [comment]
build SUCCESSFUL

it looks the android sdk has a bug, they hardcoded the AndroidManifest.xml path. it must be at the root of Android project. 
this link also gives the workaround: copy the same AndroidManifest.xml to project root(i created sym-link instead).
http://stackoverflow.com/questions/12411419/how-to-specify-path-of-androidmanifest-xml-file-in-gettype-ant-target

**Comment by friedger** [comment]
project does not support ant anymore
